quarkus:
  banner:
    enabled: false
  lambda:
    mock-event-server:
      dev-port: 8010
      test-port: 8012

app:
  connect-timeout: 12000
  request-timeout: 25000
  connection-ttl: 25000
  check-ip-server: "https://api.ipify.org"
  page-not-found-words:
    - "not found"
    - "not be found"
    - "404"
    - "did you mean"
    - "return to"
    - "oops"
    - "not exist"
    - "try again"
    - "something went wrong"
    - "no longer available"
    - "fatal error"
    - "error occurred"
    - "currently unavailable"
    - "access denied"
    - "have been moved or deleted"
    - "no results found"
    - "403 forbidden"
    - "can't find that page"
  paywall-words:
    - "paywall"
    - "unlimited"
    - "miss out"
    - "anytime"
    - "best value"
    - "join today"
    - "try free"
    - "become a subscriber"
    - "already a subscriber"
    - "subscribers only"
    - "subscribe now"
    - "get full access"
  domain-expired-words:
    - "expired"
    - "reactivate"
    - "new domain"
  user-agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.75.14 (KHTML, like Gecko) Version/7.0.3 Safari/7046A194A"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:101.0) Gecko/20100101 Firefox/101.0"

"%dev":
  quarkus:
    log:
      category:
        WebApplicationException:
          level: DEBUG
        "io.github.plantaest.feverfew.lambda":
          level: DEBUG
