quarkus:
  analytics:
    disabled: true
  http:
    port: 8000
    cors:
      ~: true
      origins:
        - http://localhost:8020
        - https://web.postman.co
        - https://feverfew.toolforge.org
  smallrye-openapi:
    info-title: Feverfew API Docs
    info-version: 0.1.0-alpha.1
    info-contact-name: Plantaest
    info-contact-url: https://meta.wikimedia.org/wiki/User:Plantaest
    info-contact-email: plantaest@gmail.com
    info-license-name: GNU Affero General Public License version 3
    info-license-url: https://www.gnu.org/licenses/agpl-3.0.html
    operation-id-strategy: METHOD
  swagger-ui:
    theme: original
    path: /api-docs
    always-include: true
    title: Feverfew API Docs
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
    default-model-expand-depth: 10
    default-models-expand-depth: 10
  log:
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) :%X{requestId}: %s%e%n"
    file:
      enable: true
      path: logs/feverfew.log
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) :%X{requestId}: %s%e%n"
      rotation:
        max-file-size: 10M
        max-backup-index: 50
        file-suffix: .yyyy-MM-dd.gz
        rotate-on-boot: true

app:
  current-result-schema-version: 1
  ignored-hosts:
    - "web.archive.org"
    - "archive.today"
    - "archive.fo"
    - "archive.is"
    - "archive.li"
    - "archive.md"
    - "archive.ph"
    - "archive.vn"
    - "archive.wikiwix.com"
    - "ghostarchive.org"
    - "webcitation.org"
    - "worldcat.org"
    - "doi.org"
    - "ncbi.nlm.nih.gov" # PMC
    - "pubmed.ncbi.nlm.nih.gov" # PMID
    - "ui.adsabs.harvard.edu" # Bibcode
    - "jstor.org"
    - "arxiv.org"
  max-non-ignored-links: 1250
  model-file-path: "model/feverfew_next_model_v1.onnx"
  aws:
    access-key-id: ${AWS_ACCESS_KEY_ID}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  lambda:
    mock-server: http://localhost:8010
    max-consecutive-invocations: 18
    batch-size: 50
    supported-regions:
      - "us-west-2"
    function-names:
      us-west-2:
        - "FeverfewRequestLinksLambda_Native_us-west-2_1"
        - "FeverfewRequestLinksLambda_Native_us-west-2_2"
        - "FeverfewRequestLinksLambda_Native_us-west-2_3"
        - "FeverfewRequestLinksLambda_Native_us-west-2_4"
  rate-limiter:
    max-size: 5000
    keep-after-refill: 20M

"%dev":
  quarkus:
    log:
      category:
        WebApplicationException:
          level: DEBUG
        "io.github.plantaest.feverfew":
          level: DEBUG
        "org.jboss.resteasy.reactive.server.handlers.ParameterHandler":
          level: DEBUG
        "org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext":
          level: DEBUG
      file:
        enable: false
    datasource:
      db-kind: mariadb
      username: root
      password: 12345
      jdbc:
        url: jdbc:mariadb://localhost:8002/feverfew

  app:
    lambda:
      function-names:
        us-west-2:
          - "FeverfewRequestLinksLambda_Native_us-west-2_1"
