quarkus:
  analytics:
    disabled: true
  http:
    port: 8000
    cors:
      ~: true
      origins:
        - http://localhost:8020
        - https://web.postman.co
        - https://feverfew.toolforge.org
  smallrye-openapi:
    info-title: Feverfew API Docs
    info-version: 0.1.0-alpha.1
    info-contact-name: Plantaest
    info-contact-url: https://meta.wikimedia.org/wiki/User:Plantaest
    info-contact-email: plantaest@gmail.com
    info-license-name: GNU Affero General Public License version 3
    info-license-url: https://www.gnu.org/licenses/agpl-3.0.html
    operation-id-strategy: METHOD
  swagger-ui:
    theme: original
    path: /api-docs
    always-include: true
    title: Feverfew API Docs
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
    default-model-expand-depth: 10
    default-models-expand-depth: 10

app:
  current-result-schema-version: 1
  ignored-hosts:
    - "web.archive.org"
    - "archive.today"
    - "archive.fo"
    - "archive.is"
    - "archive.li"
    - "archive.md"
    - "archive.ph"
    - "archive.vn"
    - "archive.wikiwix.com"
    - "ghostarchive.org"
    - "webcitation.org"
    - "worldcat.org"
    - "doi.org"
    - "ncbi.nlm.nih.gov" # PMC
    - "pubmed.ncbi.nlm.nih.gov" # PMID
    - "ui.adsabs.harvard.edu" # Bibcode
    - "jstor.org"
    - "arxiv.org"
  aws:
    access-key-id: ${AWS_ACCESS_KEY_ID}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  lambda:
    mock-server: http://localhost:8010
    max-consecutive-invocations: 18
    batch-size: 50
    supported-regions:
      - "us-west-2"
    function-names:
      us-west-2:
        - "FeverfewRequestLinksLambda_Native_us-west-2_1"
        - "FeverfewRequestLinksLambda_Native_us-west-2_2"
        - "FeverfewRequestLinksLambda_Native_us-west-2_3"
        - "FeverfewRequestLinksLambda_Native_us-west-2_4"

"%dev":
  quarkus:
    log:
      category:
        WebApplicationException:
          level: DEBUG
        "io.github.plantaest.feverfew":
          level: DEBUG
        "org.jboss.resteasy.reactive.server.handlers.ParameterHandler":
          level: DEBUG
        "org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext":
          level: DEBUG
    datasource:
      db-kind: mariadb
      username: root
      password: 12345
      jdbc:
        url: jdbc:mariadb://localhost:8002/feverfew
  app:
    lambda:
      function-names:
        us-west-2:
          - "FeverfewRequestLinksLambda_Native_us-west-2_1"
