quarkus:
  analytics:
    disabled: true
  http:
    port: 8000
    cors:
      ~: true
      origins:
        - http://localhost:8020
        - https://feverfew.toolforge.org
  smallrye-openapi:
    info-title: Feverfew API Docs
    info-version: 0.1.0-alpha.1
    info-contact-name: Plantaest
    info-contact-url: https://meta.wikimedia.org/wiki/User:Plantaest
    info-contact-email: plantaest@gmail.com
    info-license-name: GNU Affero General Public License version 3
    info-license-url: https://www.gnu.org/licenses/agpl-3.0.html
    operation-id-strategy: METHOD
  swagger-ui:
    theme: original
    path: /api-docs
    always-include: true
    title: Feverfew API Docs
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
    default-model-expand-depth: 10
    default-models-expand-depth: 10

"%dev":
  quarkus:
    log:
      category:
        WebApplicationException:
          level: DEBUG
        "io.github.plantaest.feverfew":
          level: DEBUG
        "org.jboss.resteasy.reactive.server.handlers.ParameterHandler":
          level: DEBUG
        "org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext":
          level: DEBUG
    datasource:
      db-kind: mariadb
      username: root
      password: 12345
      jdbc:
        url: jdbc:mariadb://localhost:8002/feverfew
